# Generated by Django 5.0.1 on 2024-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeKart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
