# Generated by Django 5.0.1 on 2024-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeKart', '0002_enquiry_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
